#!/bin/bash

#
# Before running this script please extract raw system image
# and mount loop image to some mount point. Give that mount point
# parameter for this script.
#
# 1. "simg2img system.img system.raw" (Run inside Mer SDK target)
# 2. "mkdir ~/system"
# 3. "sudo mount -t ext4 -o loop system.raw ~/system"
# 4. "./copy_system.sh ~/system/system"
#

if [ $# -lt 2 ]; then
  echo "Usage: $(basename $0) ~/path/to/system rpm/spec-to-modify.spec"
  exit
fi

SYSTEM_SPARSE="sparse/system"
SYSTEM_MOUNT=$1
MODIFY_SPEC=$(readlink -f $2)
POST_RULES=$(tempfile)
POST_SECTION_CREATED=0

# Add read permission for some binaries under system mount
source droid-system-device/helpers/fixup-permissions.sh

# Remove current sparse and create it again
rm -rf $SYSTEM_SPARSE
mkdir -p $SYSTEM_SPARSE

# Copy content
echo "Copy $SYSTEM_MOUNT/* to $SYSTEM_SPARSE"
rsync -a --exclude="lost+found" "$SYSTEM_MOUNT"/* "$SYSTEM_SPARSE"

pushd $SYSTEM_MOUNT 1>/dev/null
find . \( -uid +0 -or -gid +0 \) -and \( -type f -or -type d -or -type s \) -printf "[ -e /system/%P ] && chown %U:%G /system/%P\n" 2>/dev/null | sort > $POST_RULES
popd 1>/dev/null

sed -i '/# rest of this file is autogenerated. do not edit/,$d' $MODIFY_SPEC
echo "# rest of this file is autogenerated. do not edit" >> $MODIFY_SPEC

if [ $(cat $POST_RULES | wc -l) -gt 0 ]; then
  echo "Updating $MODIFY_SPEC"
  echo "%post" >> $MODIFY_SPEC
  cat $POST_RULES >> $MODIFY_SPEC
  POST_SECTION_CREATED=1
fi
rm -f $POST_RULES

if [ $POST_SECTION_CREATED -eq 0 ]; then
  echo "%post" >> $MODIFY_SPEC
fi
pushd $SYSTEM_MOUNT 1>/dev/null
find . -exec getcap {} + 2>/dev/null | awk '{ print "[ -e /system/"$1" ] && " "setcap", $3, "/system/"$1 }' | sort >> $MODIFY_SPEC
popd 1>/dev/null

# Remove generic unused directories and files
source droid-system-device/helpers/remove-unused.sh

# Move build.prop to proper place
DEVICE=$(grep ro.product.name $SYSTEM_SPARSE/build.prop | cut -d '_' -f2)
mkdir -p $DEVICE/system
mv $SYSTEM_SPARSE/build.prop $DEVICE/system
